### ISSUE TITLE
Compiling with Rack 2.2.0 using gcc 11.3 fails on simde instructions

### ISSUE THREAD

**Issue by gitterdude** [kockie69/RPJ#75]
Rack 2.2.0 apparently changed something in the simde instructions resulting in the errors below when compiling with gcc 11.3 on Ubuntu 22.04 and having -march=nehalem in Rack/compile.mk

A workaround is to replaced nehalem with -march=broadwell or skylake or compile it using an older version of gcc, like 7.5 in Ubuntu 18.04

```
build/src/SugarMice.cpp.o src/SugarMice.cpp
In file included from ../Rack/dep/include/simde/x86/sse3.h:30,
                 from ../Rack/dep/include/simde/x86/ssse3.h:30,
                 from ../Rack/dep/include/simde/x86/sse4.1.h:31,
                 from ../Rack/dep/include/simde/x86/sse4.2.h:31,
                 from ../Rack/include/simd/common.hpp:4,
                 from ../Rack/include/simd/Vector.hpp:3,
                 from ../Rack/include/simd/functions.hpp:2,
                 from ../Rack/include/dsp/common.hpp:4,
                 from ../Rack/include/rack.hpp:110,
                 from src/RPJ.hpp:1,
                 from src/PigeonPlink.cpp:5:
../Rack/dep/include/simde/x86/sse2.h:3653:30: error: redefinition of ‘__m128i simde_mm_loadu_epi64(const void*)’
 3653 |   #define _mm_loadu_epi64(a) simde_mm_loadu_epi64(a)
      |                              ^~~~~~~~~~~~~~~~~~~~
../Rack/dep/include/simde/x86/sse2.h:3633:1: note: ‘simde__m128i simde_mm_loadu_epi64(const void*)’ previously defined here
 3633 | simde_mm_loadu_epi64(void const * mem_addr) {
      | ^~~~~~~~~~~~~~~~~~~~
../Rack/dep/include/simde/x86/sse2.h:3628:30: error: redefinition of ‘__m128i simde_mm_loadu_epi32(const void*)’
 3628 |   #define _mm_loadu_epi32(a) simde_mm_loadu_epi32(a)
      |                              ^~~~~~~~~~~~~~~~~~~~
../Rack/dep/include/simde/x86/sse2.h:3608:1: note: ‘simde__m128i simde_mm_loadu_epi32(const void*)’ previously defined here
 3608 | simde_mm_loadu_epi32(void const * mem_addr) {
      | ^~~~~~~~~~~~~~~~~~~~
../Rack/dep/include/simde/x86/sse2.h:3603:30: error: redefinition of ‘__m128i simde_mm_loadu_epi16(const void*)’
 3603 |   #define _mm_loadu_epi16(a) simde_mm_loadu_epi16(a)
      |                              ^~~~~~~~~~~~~~~~~~~~

```

**Comment by gitterdude** [comment]
The Surge folks had similar problems in https://github.com/VCVRack/library/issues/745 and the suggested fix from Andrew was to remove immintrin.h :

```
--- dsp/third-party/src/SqMath.h~	2022-12-09 09:03:48.000000000 +0100
+++ dsp/third-party/src/SqMath.h	2022-12-09 11:43:14.886252391 +0100
@@ -1,7 +1,6 @@
 #pragma once
 
 #include "rack.hpp"
-#include <immintrin.h>
 #include <random>
 #if !defined(M_PI)
 #define M_PI float(3.14159265358979323846264338327950288)
```

I've verified that it compiles and works in Ubuntu 22.04

**Comment by kockie69** [comment]
Thanks, I will make the change.

**Comment by kockie69** [comment]
This has been fixed
